### ISSUE TITLE
Can't tap on TextInput for iftttApiKey?

### ISSUE THREAD

**Issue by jonginn** [kenniy/fitbit-hooks#2]
Hey Kenniy,

I bought a Versa today and this app looks perfect for what I was hoping to find!

However, it seems in Settings on the FitBit App (on my phone) I can't tap in the IFTTT API Key input to paste my key, and it won't show the placeholder either.

Am I missing something or is the [TextInput](https://github.com/kenniy/fitbit-hooks/blob/master/settings/index.jsx#L10) misconfigured? Does it require a title or label?

Cheers!

**Comment by kenniy** [comment]
hmm.. weird 🤔 .. something is definitely wrong with it.. I can reproduce this on my phone as well.. will take a look.. thanks for letting me know

**Comment by kenniy** [comment]
you are correct @jonginn .. it does require the label.. [I have updated ](https://github.com/kenniy/fitbit-hooks/pull/4/files)it in fitbit app gallery, and it should be available once approved

**Comment by kenniy** [comment]
approved and published today ..

**Comment by jonginn** [comment]
Fantastic, thanks @kenniy!
