### ISSUE TITLE
How to edit custom webhook URL?

### ISSUE THREAD

**Issue by UNIVAC-Colonel-Panic** [kenniy/fitbit-hooks#7]
I know how to add and to delete the entire custom URL, but how do I edit it? The URL could be long so I'd rather not re-enter the whole thing. I suppose as a work around if there was an option to copy the existing URL to the clipboard, then I could delete and re-add by pasting it, making changes before I save it.

**Comment by kenniy** [comment]
unfortunately, Fitbit SDK doesn't provide that functionality (as far as I know). I will add that functionality once they do.
