### ISSUE TITLE
Webhook doesn't work and doesn't display text on the screen

### ISSUE THREAD

**Issue by MikeWills** [kenniy/fitbit-hooks#9]
I finally got this configured, but I am unable to get a button to work. I have copy and pasted the API key and made sure my trigger was correct ( can you send you more info privately if needed). I am not sure why my text isn't showing up.

**Comment by kenniy** [comment]
hmm.. weird.. is this still the case. Sorry I have been quite busy. Still works for on my device. I do have "Always Connected" on though (from device settings in fitbit app). Can you confirm is there is any difference with that on?

**Comment by MikeWills** [comment]
Always Connected and All-Day Sync is both on. I am using the Versa Special Edition. Based on seeing the API, not sure the model matters.

**Comment by GeekJosh** [comment]
I got caught out by this too, could do with clearer documentation I think.

When the examples show "study:some_text", the colon is important; the left hand side of the colon is the button text, the right hand side is the IFTTT event name or the custom URL.

If you don't put the colon, the buttons do not show.

Great work on the app though, genuinely useful!

**Comment by johighley** [comment]
> I got caught out by this too, could do with clearer documentation I think.
> 
> When the examples show "study:some_text", the colon is important; the left hand side of the colon is the button text, the right hand side is the IFTTT event name or the custom URL.
> 
> If you don't put the colon, the buttons do not show.
> 
> Great work on the app though, genuinely useful!

The meaning of the colon got me also. My hooks weren't syncing and there were no error messages. I suggest changing the default text to something meaningful like "Button Label:event" and "Button Label:url". Otherwise, great little app and very useful.

**Comment by kenniy** [comment]
will be making minor updates soon and will make these clearer. thanks guys :)

**Comment by kenniy** [comment]
updated. closing this
